// Do not edit. This file is machine generated by the Resource DLL Wizard.

library NotepadPy;

{ITE} {DFMFileType} {About.dfm}
{ITE} {DFMFileType} {Main.dfm}
{ITE} {RCFileType} {Win32\Debug\NotepadPy_DRC.rc}

{$R 'About.dfm' 'AboutBox:TForm'}
{$R 'Main.dfm' 'MainForm:TForm'}
{$R 'Win32\Debug\NotepadPy_DRC.res' 'Win32\Debug\NotepadPy_DRC.rc'}

{$E ENU}

begin
end.
